name: Dispatch to Aider Agent

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    call-agent:
      uses: bwehrle/repair-agent/.github/workflows/run-agent.yaml@main
      secrets: inherit